Lab2
OFFlinea/Labs pull request #1
Opened 2024-02-19 06:54 UTC by OFFlinea

Кузнецов Иван 1 курс Б05-331

2024-03-02 22:05 UTC, KatyaProkhorchuk requested changes

2024-03-02 22:05 UTC, KatyaProkhorchuk commented on dynamic_array.cpp
> +void test1(struct Stack* st, int start);
жеательно тесты в отдельный файл

2024-03-02 22:05 UTC, KatyaProkhorchuk commented on single-linked_list.cpp
> +void test1(struct Stack* st, int start);
и тут тоже отдельно

2024-03-02 22:05 UTC, KatyaProkhorchuk commented on dynamic_array.cpp
> +            printf("No memory\n");
printf не нужно, и добавь difine для статусов 
ERROR 0
OK 1

2024-03-02 22:05 UTC, KatyaProkhorchuk commented on dynamic_array.cpp
> +            printf("No memory\n");
и тут тоже убери printf
ты же возвращаешь 0, лучше выводить текст ошибки вне функции

2024-03-02 22:05 UTC, KatyaProkhorchuk commented on single-linked_list.cpp
> +        printf("No memory\n");
тут аналогично

2024-03-12 17:32 UTC, VTroyanGolovyan commented
исправить замечания

2024-03-25 15:07 UTC, KatyaProkhorchuk requested changes

2024-03-25 15:07 UTC, KatyaProkhorchuk commented on lab2/dynamic_array.cpp
> +int main() {
я хочу использовать твой стек в своем проекте, и хочу что бы загрузив header и cpp могжно было ним пользоваться. Но у тебя в файле реализации стека находится main вызывающий тесты, зачем он тут? вывеси main к тестам

2024-03-25 15:07 UTC, KatyaProkhorchuk commented on lab2/single-linked_list.cpp
> +int main() {
то же самое замечание

2024-03-25 15:07 UTC, KatyaProkhorchuk commented on lab2/single-linked_list.cpp
> +        printf("No memory\n");
зачем вывод в конструкторе

2024-03-25 15:07 UTC, KatyaProkhorchuk commented on lab2/single-linked_list.cpp
> +        printf("No memory\n");
тут тоже, зачем
А если я использую твой стек и хочу пользователю как-то иначе сообщать от ошибке, или вообще ничего не выводить в консоль...

2024-03-25 15:07 UTC, KatyaProkhorchuk commented on lab2/dynamic_array.cpp
> +            return ERROR;
получается что без файла тестов программа не знает что такое ERROR
лучше объявлять define в header

2024-03-31 22:57 UTC, VTroyanGolovyan commented
ping

2024-04-02 16:22 UTC, KatyaProkhorchuk requested changes
в выводе не указано почему стек на динамическом массиве лучше

2024-04-02 16:22 UTC, KatyaProkhorchuk commented on lab2/dynamic_array.cpp
только не cpp, а с

2024-04-15 07:37 UTC, VTroyanGolovyan approved these changes

2024-04-15 07:37 UTC, VTroyanGolovyan commented on lab2/dynamic_array.c
> +void print_stack(struct Stack* st) {
const

2024-04-15 07:37 UTC, VTroyanGolovyan commented on lab2/list_functions.h
> +int top(struct Stack* st, void* buffer);
const stack

2024-04-15 07:37 UTC, VTroyanGolovyan commented on lab2/tests.c
> +int main() {
int argc, char** argv

2024-04-15 07:38 UTC, merged