Lab3 Кузнецов Иван Б05-331
OFFlinea/Labs pull request #2
Opened 2024-03-24 13:12 UTC by OFFlinea

Сделал лабу по сортировкам, ура

2024-03-29 23:33 UTC, KatyaProkhorchuk requested changes

2024-03-29 23:33 UTC, KatyaProkhorchuk commented on lab3/generator_sort.cpp
> +        scanf("%d", &array[i]);
проверку нужно добавить

2024-03-29 23:33 UTC, KatyaProkhorchuk commented on lab3/merge_sort.h
> +    }
а где free `sorted_array`

2024-04-06 23:54 UTC, KatyaProkhorchuk requested changes

2024-04-06 23:54 UTC, KatyaProkhorchuk commented on lab3/bubble_sort.h
> +                temp = arr[j];
реализуй swap и используй его

2024-04-06 23:54 UTC, KatyaProkhorchuk commented on lab3/heap_sort.h
> +        int child = i * k + j;
реализуй get_child

2024-04-06 23:54 UTC, KatyaProkhorchuk commented on lab3/heap_sort.h
> +        int temp = array[0];
swap

2024-04-06 23:54 UTC, KatyaProkhorchuk commented on lab3/merge_sort.h
> +        printf("No memory\n");
возвращай статус - не надо ничего выводить

2024-04-06 23:54 UTC, KatyaProkhorchuk commented on lab3/selection_sort.h
> +        temp = arr[min_idx];
swap

2024-04-15 23:05 UTC, VTroyanGolovyan commented
У ТЕБЯ МЕРДЖ КОНФЛИКТЫ
исправь

2024-04-15 23:05 UTC, VTroyanGolovyan requested changes
КОНФЛИКТЫ

2024-04-20 21:47 UTC, VTroyanGolovyan commented
Последнее для тебя предупреждение не использовать веб интерфейс для комитов

2024-04-26 21:43 UTC, VTroyanGolovyan requested changes
И напиши makefile

2024-04-26 21:43 UTC, VTroyanGolovyan commented on lab3/graphics/paragraph_8_graphic.png
Назови графики нормально

2024-04-26 21:43 UTC, VTroyanGolovyan commented on lab3/quick_sort.h
разбей .h и .c

2024-04-26 21:43 UTC, VTroyanGolovyan commented on lab3/heap_sort.h
> +#ifndef HEAP_SORT_H
везде разбить

2024-05-05 12:00 UTC, VTroyanGolovyan requested changes
чутка осталось

2024-05-05 12:00 UTC, VTroyanGolovyan commented on lab3/generator_sort.cpp
> +    return *((const int*) num1) - *((const int*) num2);
мне не нравится этот компаратор, привести пример когда будет переполнение
Как сделать без него?
Можно ли написать его без if

2024-05-05 12:00 UTC, VTroyanGolovyan commented on lab3/quick_sort.h
> +void Hoare_quick_sort(int* array, int n);
в h файле оставь только те функции которые нужны потом чтоб их вызывать (это всего касается)
у тебя еще стиль нейминга разный, сделай в одном

2024-05-05 12:00 UTC, VTroyanGolovyan commented on lab3/quick_sort.c
> +    int random3 = low + rand() % (high - low + 1);
зачем три раза считать high - low + 1

2024-05-07 21:33 UTC, VTroyanGolovyan approved these changes
Давай приму уже=)

2024-05-07 21:40 UTC, merged